[package]
name = "immutable-json"
version = "1.2.0"
edition = "2024"
description = "Immutable JSON transformations"
homepage = "https://github.com/wdonne/immutable-json"
repository = "https://github.com/wdonne/immutable-json"
license = "BSD-2-Clause"
readme = "README.md"
keywords = ["json", "immutable"]
exclude = ["*.iml"]

[dependencies]
imbl = "7.0.0"
imbl-util = "1.0.0"
serde_json = "1.0.150"
take-until = "0.2.0"
bytes = { version = "1.12.0", optional = true }
jaq-core = { version = "3.1.0", optional = true }
jaq-std = {  version = "3.0.1", optional = true }
jaq-json = { version = "2.0.1", optional = true }
json-patch = { version = "4.2.0", optional = true }

[features]
jaq = ["dep:bytes", "dep:jaq-core", "dep:jaq-std", "dep:jaq-json"]
patch = ["dep:json-patch"]
